language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - extra-android-support
    - extra-android-m2repository

script:
    - ./gradlew check -i
    - ./gradlew assemble

after_failure:
  - cat /home/travis/build/Bilibili/DanmakuFlameMaster/DanmakuFlameMaster/build/outputs/lint-results.html
  - cat /home/travis/build/Bilibili/DanmakuFlameMaster/DanmakuFlameMaster/build/outputs/lint-results.xml
